apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Make sure this matches the size of the PV
  volumeMode: Filesystem
  volumeName: mysql-pv  # This must match the PV name

