apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 767398131861.dkr.ecr.us-east-1.amazonaws.com/node:latest # Replace with your Node.js app image
          env:
            - name: DB_HOST
              value: "mysql-service"  # MySQL service name
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"  # Hardcoded password
            - name: DB_NAME
              value: "node_app"
            - name: APP_PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: node-app
  type: LoadBalancer
